apiVersion: apps/v1
kind: Deployment
metadata:
  name: fitness-tracker-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fitness-tracker-app
  template:
    metadata:
      labels:
        app: fitness-tracker-app
      annotations:
        ad.datadoghq.com/fitness-tracker-app.logs: '[{"source":"nodejs","service":"fitness-tracker-service"},{"source":"nodejs","service":"fitness-tracker-app"}]'
    spec:
      containers:
      - name: fitness-tracker-app
        image: pulkit197/fitness_tracker-master-copy3-fitness-app:latest
        ports:
        - containerPort: 5000
        envFrom:
          - configMapRef:
            name: fitness-configmap
        #- name: MONGODB_URI
          #valueFrom:
            #configMapKeyRef:
             # name: fitness-configmap
             # key: MONGODB_URI
        #- name: PORT
          #valueFrom:
            #configMapKeyRef:
              #name: fitness-configmap
              #key: PORT
       # - name: HOST
          #valueFrom:
           # configMapKeyRef:
           #   name: fitness-configmap
           #   key: HOST
        #- name: NODE_ENV
         # valueFrom:
           # configMapKeyRef:
             # name: fitness-configmap
             # key: NODE_ENV 
        # Datadog APM (tracing) env variables
        - name: DD_AGENT_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: DD_TRACE_AGENT_PORT
          value: "8126"
        - name: DD_ENV
          value: "production"
        - name: DD_SERVICE
          value: "fitness-tracker-app"
        - name: DD_VERSION
          value: "1.0.0"
---
apiVersion: v1
kind: Service
metadata:
  name: fitness-tracker-service
spec:
  selector:
    app: fitness-tracker-app
  ports:
  - port: 80
    targetPort: 5000
  type: LoadBalancer
