apiVersion: v1 
kind: Configmap 
metadata:
  name: fitness-configmap 
data:
  MONGODB_URI: "mongodb://mongodb-service:27017/fitness-tracker"
  PORT: "5000"
  HOST: "0.0.0.0"
  NODE_ENV: "production"



    